function [r,dr] = rdrIRK(deltaT,xk,in3,in4,lambda)
%rdrIRK
%    [R,DR] = rdrIRK(deltaT,XK,IN3,IN4,LAMBDA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Oct-2023 20:12:02

A1_1 = in4(1);
A1_2 = in4(3);
A2_1 = in4(2);
A2_2 = in4(4);
K1 = in3(1,:);
K2 = in3(2,:);
r = [-K1+lambda.*(xk+A1_1.*K1.*deltaT+A1_2.*K2.*deltaT);-K2+lambda.*(xk+A2_1.*K1.*deltaT+A2_2.*K2.*deltaT)];
if nargout > 1
    dr = reshape([A1_1.*deltaT.*lambda-1.0,A2_1.*deltaT.*lambda,A1_2.*deltaT.*lambda,A2_2.*deltaT.*lambda-1.0],[2,2]);
end
