function [r,dr] = rdrIRK(deltaT,t,xk,in4,in5,lambda)
%rdrIRK
%    [R,DR] = rdrIRK(deltaT,T,XK,IN4,IN5,LAMBDA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Oct-2023 15:57:44

A1_1 = in5(1);
A1_2 = in5(3);
A2_1 = in5(2);
A2_2 = in5(4);
K1 = in4(1,:);
K2 = in4(2,:);
r = [-K1+lambda.*(xk+A1_1.*K1.*deltaT+A1_2.*K2.*deltaT);-K2+lambda.*(xk+A2_1.*K1.*deltaT+A2_2.*K2.*deltaT)];
if nargout > 1
    dr = reshape([A1_1.*deltaT.*lambda-1.0,A2_1.*deltaT.*lambda,A1_2.*deltaT.*lambda,A2_2.*deltaT.*lambda-1.0],[2,2]);
end
